### ISSUE TITLE
Errors when trying to install rchess, help?

### ISSUE THREAD

**Issue by sjqtentacles** [srfoster/rchess#2]
Hello! From the looks of the documentation I think this is a great package. I wanted to use it for one of my chess projects, but I'm having trouble installing it using DrRacket. I pasted the error below, I'm wondering if you can make sense of it? I'm using DrRacket 7.3 on OS X. I wonder if you yourself can install it, or if it's just my own problem? I think I had the same issue trying to install it on Mint or Ubuntu a few months ago but I wanted to try it again on a Mac. Anyway thanks for uploading the code, maybe I can piece some of it together myself if the installation doesn't work. 

> Resolving "rchess" via https://download.racket-lang.org/releases/7.3/catalog/
> Resolving "rchess" via https://pkgs.racket-lang.org
> Using cached15826568531582656853600 for https://github.com/srfoster/rchess.git
> raco setup: version: 7.3
> raco setup: platform: x86_64-macosx [3m]
> raco setup: target machine: racket
> raco setup: installation name: 7.3
> raco setup: variants: 3m
> raco setup: main collects: /Applications/Racket v7.3/collects
> raco setup: collects paths: 
> raco setup:   /Users/azsarki/Library/Racket/7.3/collects
> raco setup:   /Applications/Racket v7.3/collects
> raco setup: main pkgs: /Applications/Racket v7.3/share/pkgs
> raco setup: pkgs paths: 
> raco setup:   /Applications/Racket v7.3/share/pkgs
> raco setup:   /Users/azsarki/Library/Racket/7.3/pkgs
> raco setup: links files: 
> raco setup:   /Applications/Racket v7.3/share/links.rktd
> raco setup:   /Users/azsarki/Library/Racket/7.3/links.rktd
> raco setup: main docs: /Applications/Racket v7.3/doc
> raco setup: --- updating info-domain tables ---                    [14:00:20]
> raco setup: updating: /Users/azsarki/Library/Racket/7.3/share/info-cache.rktd
> raco setup: --- pre-installing collections ---                     [14:00:20]
> raco setup: --- installing foreign libraries ---                   [14:00:20]
> raco setup: --- installing shared files ---                        [14:00:20]
> raco setup: --- compiling collections ---                          [14:00:20]
> raco setup: --- parallel build using 4 jobs ---                    [14:00:20]
> raco setup: 3 making: <pkgs>/rchess
> raco setup: 3 making: <pkgs>/rchess/fen
> raco setup: 3 making: <pkgs>/rchess/images
> raco setup: 3 making: <pkgs>/rchess/moves
> application: procedure does not expect an argument with given keyword
>   procedure: format-id
>   given keyword: #:subs?
>   arguments...:
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    "constructor:~a"
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    #:subs? #t
>   compilation context...:
>    /Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt
>    /Users/azsarki/Library/Racket/7.3/pkgs/rebellion/type/tuple.rkt
>    /Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/record-type-base.rkt
>    /Users/azsarki/Library/Racket/7.3/pkgs/rebellion/type/record/base.rkt
>    /Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/record-type.rkt
>    /Users/azsarki/Library/Racket/7.3/pkgs/rebellion/type/record.rkt
>    /Users/azsarki/Library/Racket/7.3/pkgs/chess/piece.rkt
>    /Users/azsarki/Library/Racket/7.3/pkgs/chess/board.rkt
>    /Users/azsarki/Library/Racket/7.3/pkgs/chess/main.rkt
>    /Users/azsarki/Library/Racket/7.3/pkgs/rchess/images/main.rkt
>    /Users/azsarki/Library/Racket/7.3/pkgs/rchess/main.rkt
>   context...:
>    /Applications/Racket v7.3/collects/racket/private/kw.rkt:1483:14
>    /Applications/Racket v7.3/collects/syntax/parse/private/parse.rkt:1044:13: dots-loop
>    /Applications/Racket v7.3/collects/syntax/parse/define.rkt:13:9: define-tuple-type
>    apply-transformer-in-context
>    apply-transformer52
>    dispatch-transformer41
>    loop
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    for-loop
>    [repeats 1 more time]
>    finish-bodys
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    ...
> application: procedure does not expect an argument with given keyword
>   procedure: format-id
>   given keyword: #:subs?
>   arguments...:
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    "constructor:~a"
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    #:subs? #t
>   compilation context...:
>    /Users/azsarki/Library/Racket/7.3/pkgs/rchess/moves/current-board.rkt
>   context...:
>    /Applications/Racket v7.3/collects/racket/private/kw.rkt:1483:14
>    /Applications/Racket v7.3/collects/syntax/parse/private/parse.rkt:1044:13: dots-loop
>    /Applications/Racket v7.3/collects/syntax/parse/define.rkt:13:9: define-tuple-type
>    apply-transformer-in-context
>    apply-transformer52
>    dispatch-transformer41
>    loop
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    for-loop
>    [repeats 1 more time]
>    finish-bodys
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    ...
> application: procedure does not expect an argument with given keyword
>   procedure: format-id
>   given keyword: #:subs?
>   arguments...:
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    "constructor:~a"
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    #:subs? #t
>   compilation context...:
>    /Users/azsarki/Library/Racket/7.3/pkgs/rchess/pgn/main.rkt
>    /Users/azsarki/Library/Racket/7.3/pkgs/rchess/pgn.rkt
>   context...:
>    /Applications/Racket v7.3/collects/racket/private/kw.rkt:1483:14
>    /Applications/Racket v7.3/collects/syntax/parse/private/parse.rkt:1044:13: dots-loop
>    /Applications/Racket v7.3/collects/syntax/parse/define.rkt:13:9: define-tuple-type
>    apply-transformer-in-context
>    apply-transformer52
>    dispatch-transformer41
>    loop
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    for-loop
>    [repeats 1 more time]
>    finish-bodys
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    ...
> application: procedure does not expect an argument with given keyword
>   procedure: format-id
>   given keyword: #:subs?
>   arguments...:
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    "constructor:~a"
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    #:subs? #t
>   compilation context...:
>    /Users/azsarki/Library/Racket/7.3/pkgs/rchess/moves/all-squares.rkt
>   context...:
>    /Applications/Racket v7.3/collects/racket/private/kw.rkt:1483:14
>    /Applications/Racket v7.3/collects/syntax/parse/private/parse.rkt:1044:13: dots-loop
>    /Applications/Racket v7.3/collects/syntax/parse/define.rkt:13:9: define-tuple-type
>    apply-transformer-in-context
>    apply-transformer52
>    dispatch-transformer41
>    loop
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    for-loop
>    [repeats 1 more time]
>    finish-bodys
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    ...
> raco setup: 3 making: <pkgs>/rchess/pgn
> application: procedure does not expect an argument with given keyword
>   procedure: format-id
>   given keyword: #:subs?
>   arguments...:
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    "constructor:~a"
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    #:subs? #t
>   compilation context...:
>    /Users/azsarki/Library/Racket/7.3/pkgs/rchess/scribblings/rchess.scrbl
>   context...:
>    /Applications/Racket v7.3/collects/racket/private/kw.rkt:1483:14
>    /Applications/Racket v7.3/collects/syntax/parse/private/parse.rkt:1044:13: dots-loop
>    /Applications/Racket v7.3/collects/syntax/parse/define.rkt:13:9: define-tuple-type
>    apply-transformer-in-context
>    apply-transformer52
>    dispatch-transformer41
>    loop
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    for-loop
>    [repeats 1 more time]
>    finish-bodys
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    ...
> application: procedure does not expect an argument with given keyword
>   procedure: format-id
>   given keyword: #:subs?
>   arguments...:
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    "constructor:~a"
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    #:subs? #t
>   compilation context...:
>    /Users/azsarki/Library/Racket/7.3/pkgs/rchess/moves/main.rkt
>   context...:
>    /Applications/Racket v7.3/collects/racket/private/kw.rkt:1483:14
>    /Applications/Racket v7.3/collects/syntax/parse/private/parse.rkt:1044:13: dots-loop
>    /Applications/Racket v7.3/collects/syntax/parse/define.rkt:13:9: define-tuple-type
>    apply-transformer-in-context
>    apply-transformer52
>    dispatch-transformer41
>    loop
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    for-loop
>    [repeats 1 more time]
>    finish-bodys
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    ...
> application: procedure does not expect an argument with given keyword
>   procedure: format-id
>   given keyword: #:subs?
>   arguments...:
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    "constructor:~a"
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    #:subs? #t
>   compilation context...:
>    /Users/azsarki/Library/Racket/7.3/pkgs/rchess/moves/move.rkt
>   context...:
>    /Applications/Racket v7.3/collects/racket/private/kw.rkt:1483:14
>    /Applications/Racket v7.3/collects/syntax/parse/private/parse.rkt:1044:13: dots-loop
>    /Applications/Racket v7.3/collects/syntax/parse/define.rkt:13:9: define-tuple-type
>    apply-transformer-in-context
>    apply-transformer52
>    dispatch-transformer41
>    loop
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    for-loop
>    [repeats 1 more time]
>    finish-bodys
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    ...
> raco setup: 3 making: <pkgs>/rchess/puzzles
> application: procedure does not expect an argument with given keyword
>   procedure: format-id
>   given keyword: #:subs?
>   arguments...:
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    "constructor:~a"
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    #:subs? #t
>   compilation context...:
>    /Users/azsarki/Library/Racket/7.3/pkgs/rchess/moves/util.rkt
>   context...:
>    /Applications/Racket v7.3/collects/racket/private/kw.rkt:1483:14
>    /Applications/Racket v7.3/collects/syntax/parse/private/parse.rkt:1044:13: dots-loop
>    /Applications/Racket v7.3/collects/syntax/parse/define.rkt:13:9: define-tuple-type
>    apply-transformer-in-context
>    apply-transformer52
>    dispatch-transformer41
>    loop
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    for-loop
>    [repeats 1 more time]
>    finish-bodys
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    ...
> raco setup: 3 making: <pkgs>/rchess/puzzles/chessblunders
> application: procedure does not expect an argument with given keyword
>   procedure: format-id
>   given keyword: #:subs?
>   arguments...:
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    "constructor:~a"
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    #:subs? #t
>   compilation context...:
>    /Users/azsarki/Library/Racket/7.3/pkgs/rchess/pgn/deepblue-kasparov-1997.rkt
>   context...:
>    /Applications/Racket v7.3/collects/racket/private/kw.rkt:1483:14
>    /Applications/Racket v7.3/collects/syntax/parse/private/parse.rkt:1044:13: dots-loop
>    /Applications/Racket v7.3/collects/syntax/parse/define.rkt:13:9: define-tuple-type
>    apply-transformer-in-context
>    apply-transformer52
>    dispatch-transformer41
>    loop
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    for-loop
>    [repeats 1 more time]
>    finish-bodys
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    ...
> raco setup: 3 making: <pkgs>/rchess/puzzles/chessblunders/chessblunders-cache
> application: procedure does not expect an argument with given keyword
>   procedure: format-id
>   given keyword: #:subs?
>   arguments...:
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    "constructor:~a"
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    #:subs? #t
>   compilation context...:
>    /Users/azsarki/Library/Racket/7.3/pkgs/rchess/pgn/napoleon-turk-1809.rkt
>   context...:
>    /Applications/Racket v7.3/collects/racket/private/kw.rkt:1483:14
>    /Applications/Racket v7.3/collects/syntax/parse/private/parse.rkt:1044:13: dots-loop
>    /Applications/Racket v7.3/collects/syntax/parse/define.rkt:13:9: define-tuple-type
>    apply-transformer-in-context
>    apply-transformer52
>    dispatch-transformer41
>    loop
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    for-loop
>    [repeats 1 more time]
>    finish-bodys
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    ...
> raco setup: 3 making: <pkgs>/rchess/scribblings
> raco setup: 3 making: <pkgs>/rchess/test
> application: procedure does not expect an argument with given keyword
>   procedure: format-id
>   given keyword: #:subs?
>   arguments...:
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    "constructor:~a"
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    #:subs? #t
>   compilation context...:
>    /Users/azsarki/Library/Racket/7.3/pkgs/rchess/pgn/patch-test.rkt
>   context...:
>    /Applications/Racket v7.3/collects/racket/private/kw.rkt:1483:14
>    /Applications/Racket v7.3/collects/syntax/parse/private/parse.rkt:1044:13: dots-loop
>    /Applications/Racket v7.3/collects/syntax/parse/define.rkt:13:9: define-tuple-type
>    apply-transformer-in-context
>    apply-transformer52
>    dispatch-transformer41
>    loop
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    for-loop
>    [repeats 1 more time]
>    finish-bodys
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    ...
> application: procedure does not expect an argument with given keyword
>   procedure: format-id
>   given keyword: #:subs?
>   arguments...:
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    "constructor:~a"
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    #:subs? #t
>   compilation context...:
>    /Users/azsarki/Library/Racket/7.3/pkgs/rchess/puzzles/chessblunders/main.rkt
>    /Users/azsarki/Library/Racket/7.3/pkgs/rchess/puzzles/main.rkt
>   context...:
>    /Applications/Racket v7.3/collects/racket/private/kw.rkt:1483:14
>    /Applications/Racket v7.3/collects/syntax/parse/private/parse.rkt:1044:13: dots-loop
>    /Applications/Racket v7.3/collects/syntax/parse/define.rkt:13:9: define-tuple-type
>    apply-transformer-in-context
>    apply-transformer52
>    dispatch-transformer41
>    loop
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    for-loop
>    [repeats 1 more time]
>    finish-bodys
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    ...
> application: procedure does not expect an argument with given keyword
>   procedure: format-id
>   given keyword: #:subs?
>   arguments...:
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    "constructor:~a"
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    #:subs? #t
>   compilation context...:
>    /Users/azsarki/Library/Racket/7.3/pkgs/rchess/test/main.rkt
>   context...:
>    /Applications/Racket v7.3/collects/racket/private/kw.rkt:1483:14
>    /Applications/Racket v7.3/collects/syntax/parse/private/parse.rkt:1044:13: dots-loop
>    /Applications/Racket v7.3/collects/syntax/parse/define.rkt:13:9: define-tuple-type
>    apply-transformer-in-context
>    apply-transformer52
>    dispatch-transformer41
>    loop
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    for-loop
>    [repeats 1 more time]
>    finish-bodys
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    ...
> raco setup: --- creating launchers ---                             [14:00:26]
> raco setup: --- installing man pages ---                           [14:00:26]
> raco setup: --- building documentation ---                         [14:00:26]
> raco setup: 1 skipping: <pkgs>/chess/main.scrbl
> raco setup: 2 skipping: <pkgs>/pfds/pfds/scribblings/functional-data-structures.scrbl
> raco setup: 2 skipping: <pkgs>/pict3d/pict3d/scribblings/pict3d.scrbl
> raco setup: 1 skipping: <pkgs>/ppict/ppict.scrbl
> raco setup: 2 running: <pkgs>/rchess/scribblings/rchess.scrbl
> raco setup: 1 skipping: <pkgs>/rebellion/main.scrbl
> raco setup: 0 skipping: <pkgs>/staged-slide/scribblings/staged-slide.scrbl
> raco setup: 0 skipping: <pkgs>/pict3d/typed/opengl/typed-opengl.scrbl
> application: procedure does not expect an argument with given keyword
>   procedure: format-id
>   given keyword: #:subs?
>   arguments...:
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    "constructor:~a"
>    #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
>    #:subs? #t
>   context...:
>    /Applications/Racket v7.3/collects/racket/private/kw.rkt:1483:14
>    /Applications/Racket v7.3/collects/syntax/parse/private/parse.rkt:1044:13: dots-loop
>    /Applications/Racket v7.3/collects/syntax/parse/define.rkt:13:9: define-tuple-type
>    apply-transformer-in-context
>    apply-transformer52
>    dispatch-transformer41
>    loop
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    for-loop
>    [repeats 1 more time]
>    finish-bodys
>    for-loop
>    finish-bodys
>    lambda-clause-expander
>    ...
> 
>   context...:
>    /Applications/Racket v7.3/collects/setup/parallel-do.rkt:332:4: work-done method in list-queue%
>    /Applications/Racket v7.3/collects/setup/parallel-do.rkt:282:17
>    /Applications/Racket v7.3/collects/setup/parallel-do.rkt:236:4
>    /Applications/Racket v7.3/share/pkgs/racket-index/setup/scribble.rkt:138:0: setup-scribblings
>    /Applications/Racket v7.3/collects/setup/setup-core.rkt:72:0: setup-core
>    /Applications/Racket v7.3/collects/setup/setup.rkt:78:3
>    /Applications/Racket v7.3/collects/pkg/main.rkt:17:0: setup
>    /Applications/Racket v7.3/collects/racket/contract/private/arrow-higher-order.rkt:360:33
>    /Applications/Racket v7.3/share/pkgs/gui-lib/mrlib/terminal.rkt:213:7
>    /Applications/Racket v7.3/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:435:6
>    /Applications/Racket v7.3/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:486:32
>    /Applications/Racket v7.3/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
>    /Applications/Racket v7.3/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:370:11: eventspace-handler-thread-proc
> raco setup: --- installing collections ---                         [14:00:35]
> raco setup: --- post-installing collections ---                    [14:00:35]
> raco setup: --- summary of errors ---                              [14:00:35]
> raco setup: error: during making for <pkgs>/rchess
> raco setup:   application: procedure does not expect an argument with given keyword
> raco setup:     procedure: format-id
> raco setup:     given keyword: #:subs?
> raco setup:     arguments...:
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      "constructor:~a"
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      #:subs? #t
> raco setup:     compiling: <pkgs>/rebellion/private/tuple-type.rkt
> raco setup: error: during making for <pkgs>/rchess/moves
> raco setup:   application: procedure does not expect an argument with given keyword
> raco setup:     procedure: format-id
> raco setup:     given keyword: #:subs?
> raco setup:     arguments...:
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      "constructor:~a"
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      #:subs? #t
> raco setup:     compiling: <pkgs>/rchess/moves/current-board.rkt
> raco setup: error: during making for <pkgs>/rchess
> raco setup:   application: procedure does not expect an argument with given keyword
> raco setup:     procedure: format-id
> raco setup:     given keyword: #:subs?
> raco setup:     arguments...:
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      "constructor:~a"
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      #:subs? #t
> raco setup:     compiling: <pkgs>/rchess/pgn/main.rkt
> raco setup: error: during making for <pkgs>/rchess/moves
> raco setup:   application: procedure does not expect an argument with given keyword
> raco setup:     procedure: format-id
> raco setup:     given keyword: #:subs?
> raco setup:     arguments...:
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      "constructor:~a"
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      #:subs? #t
> raco setup:     compiling: <pkgs>/rchess/moves/all-squares.rkt
> raco setup: error: during making for <pkgs>/rchess
> raco setup:   application: procedure does not expect an argument with given keyword
> raco setup:     procedure: format-id
> raco setup:     given keyword: #:subs?
> raco setup:     arguments...:
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      "constructor:~a"
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      #:subs? #t
> raco setup:     compiling: <pkgs>/rchess/scribblings/rchess.scrbl
> raco setup: error: during making for <pkgs>/rchess/moves
> raco setup:   application: procedure does not expect an argument with given keyword
> raco setup:     procedure: format-id
> raco setup:     given keyword: #:subs?
> raco setup:     arguments...:
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      "constructor:~a"
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      #:subs? #t
> raco setup:     compiling: <pkgs>/rchess/moves/main.rkt
> raco setup: error: during making for <pkgs>/rchess/moves
> raco setup:   application: procedure does not expect an argument with given keyword
> raco setup:     procedure: format-id
> raco setup:     given keyword: #:subs?
> raco setup:     arguments...:
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      "constructor:~a"
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      #:subs? #t
> raco setup:     compiling: <pkgs>/rchess/moves/move.rkt
> raco setup: error: during making for <pkgs>/rchess/moves
> raco setup:   application: procedure does not expect an argument with given keyword
> raco setup:     procedure: format-id
> raco setup:     given keyword: #:subs?
> raco setup:     arguments...:
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      "constructor:~a"
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      #:subs? #t
> raco setup:     compiling: <pkgs>/rchess/moves/util.rkt
> raco setup: error: during making for <pkgs>/rchess/pgn
> raco setup:   application: procedure does not expect an argument with given keyword
> raco setup:     procedure: format-id
> raco setup:     given keyword: #:subs?
> raco setup:     arguments...:
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      "constructor:~a"
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      #:subs? #t
> raco setup:     compiling: <pkgs>/rchess/pgn/deepblue-kasparov-1997.rkt
> raco setup: error: during making for <pkgs>/rchess/pgn
> raco setup:   application: procedure does not expect an argument with given keyword
> raco setup:     procedure: format-id
> raco setup:     given keyword: #:subs?
> raco setup:     arguments...:
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      "constructor:~a"
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      #:subs? #t
> raco setup:     compiling: <pkgs>/rchess/pgn/napoleon-turk-1809.rkt
> raco setup: error: during making for <pkgs>/rchess/pgn
> raco setup:   application: procedure does not expect an argument with given keyword
> raco setup:     procedure: format-id
> raco setup:     given keyword: #:subs?
> raco setup:     arguments...:
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      "constructor:~a"
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      #:subs? #t
> raco setup:     compiling: <pkgs>/rchess/pgn/patch-test.rkt
> raco setup: error: during making for <pkgs>/rchess/puzzles
> raco setup:   application: procedure does not expect an argument with given keyword
> raco setup:     procedure: format-id
> raco setup:     given keyword: #:subs?
> raco setup:     arguments...:
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      "constructor:~a"
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      #:subs? #t
> raco setup:     compiling: <pkgs>/rchess/puzzles/chessblunders/main.rkt
> raco setup: error: during making for <pkgs>/rchess/test
> raco setup:   application: procedure does not expect an argument with given keyword
> raco setup:     procedure: format-id
> raco setup:     given keyword: #:subs?
> raco setup:     arguments...:
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      "constructor:~a"
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      #:subs? #t
> raco setup:     compiling: <pkgs>/rchess/test/main.rkt
> raco setup: error: during building docs for <pkgs>/rchess/scribblings/rchess.scrbl
> raco setup:   application: procedure does not expect an argument with given keyword
> raco setup:     procedure: format-id
> raco setup:     given keyword: #:subs?
> raco setup:     arguments...:
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      "constructor:~a"
> raco setup:      #<syntax:Users/azsarki/Library/Racket/7.3/pkgs/rebellion/private/tuple-type.rkt:68:23 point>
> raco setup:      #:subs? #t
> raco setup:     context...:
> raco setup:      /Applications/Racket v7.3/collects/racket/private/kw.rkt:1483:14
> raco setup:      /Applications/Racket v7.3/collects/syntax/parse/private/parse.rkt:1044:13: dots-loop
> raco setup:      /Applications/Racket v7.3/collects/syntax/parse/define.rkt:13:9: define-tuple-type
> raco setup:      apply-transformer-in-context
> raco setup:      apply-transformer52
> raco setup:      dispatch-transformer41
> raco setup:      loop
> raco setup:      for-loop
> raco setup:      finish-bodys
> raco setup:      lambda-clause-expander
> raco setup:      for-loop
> raco setup:      [repeats 1 more time]
> raco setup:      finish-bodys
> raco setup:      for-loop
> raco setup:      finish-bodys
> raco setup:      lambda-clause-expander
> raco setup:      ...
> raco setup:   
> DrRacket install: packages installed, although setup reported errors
>

**Comment by srfoster** [comment]
Interesting.  I can confirm I was able to install it on my Ubuntu machine just now, on Racket 7.5.  I've also installed in on a Mac before (probably with Racket 7.3 or 7.4).

The logs make it look like the issue might be with the `rebellion` library.  Are you able to install Rebellion on its own and use it?

https://github.com/jackfirth/rebellion

**Comment by sjqtentacles** [comment]
Oh good catch, I'm still new to reading Racket logs. Rebellion failed to install, I guess that was the problem the whole time.
